name: Fetch Google Sheets → JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # every 2 hours (UTC)

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run fetch-sheets.mjs
        run: |
          node "Revision Hub V3/assets/scripts/fetch-sheets.mjs"

      - name: Commit JSON updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update JSON data from Google Sheets"
          file_pattern: 'Revision Hub V3/assets/data/*.json'
